substitutions:
  relay_restore_mode: RESTORE_DEFAULT_OFF 
  devicename: device #wpropumpvoltge
  hlw8012_update_interval: 5s
  friendly_name: friendly_name
  device_description: "BN-LINK BNC-60 U133TJ Plug with Energy"
  current_resistor: "0.004536" #"0.001" <- Calibrated using this factory value. Calibrate current_resistor = (current_resistor_value * I_raw) / I_actua
  voltage_divider: "830.379" #"1600" <- Calibrated using this factory value. Calibrate using voltage_divider = (current_voltage_divider_value * V_actual) / V_raw

esphome:
  name: ${devicename}
  friendly_name: ${friendly_name}
  comment: ${device_description}

bk72xx:
  board: wb2s

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "keyHere"

ota:
  - platform: esphome
    password: "passwordHere"

wifi:
  networks:
  - ssid: !secret wifi_ssid
    password: !secret wifi_password
  
#  - ssid: !secret wifi2_ssid
#    password: !secret wifi2_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Bnlink Fallback Hotspot"
    password: "passwordHere"

captive_portal:

debug:
  update_interval: 5s

globals:
  - id: total_energy
    type: float
    restore_value: yes
    initial_value: '0.0'
  
sensor:
  - platform: uptime
    name: Uptime
    update_interval: 5min

  - platform: wifi_signal
    name: "WiFi Signal"
    update_interval: 5min
    
  - platform: hlw8012
    model: BL0937
    
    cf_pin:
      number: GPIO7
      inverted: true

    cf1_pin:
      number: GPIO8
      inverted: true

    sel_pin:
      number: GPIO24
      inverted: true

    change_mode_every: 3
    initial_mode: VOLTAGE  # Start with voltage measurement
    update_interval: ${hlw8012_update_interval}

    current_resistor: ${current_resistor}
    voltage_divider: ${voltage_divider}

    voltage:
      name: "Voltage"
      id: PlugVoltage
      unit_of_measurement: V
      accuracy_decimals: 2
      # Remove filters during calibration

    current:
      name: "Current"
      id: PlugCurrent
      unit_of_measurement: A
      accuracy_decimals: 3
      # Remove filters during calibration

    power:
      name: "Power"
      id: PlugPower
      unit_of_measurement: W
      accuracy_decimals: 1
      filters:
        - lambda: if (x < 0.5) {return 0;} else {return x;}  # 0.5W threshold
        # Add multiply filter AFTER calibration if needed

  # Reports the total Power so-far each day
  - platform: total_daily_energy
    name: Total Daily Energy
    icon: mdi:circle-slice-3
    power_id: PlugPower
    filters:
      - multiply: 0.001
    unit_of_measurement: kWh

binary_sensor:
  - platform: gpio
    id: binary_switch_1
    device_class: window
    pin:
      number: P10
      inverted: true
      mode: INPUT_PULLUP
    on_press:
      then:
        - switch.toggle: switch_1

output:
  - platform: libretiny_pwm
    id: output_led_1
    pin:
      number: P23
      inverted: true

light:
  - platform: status_led
    id: plug_led
    output: output_led_1

switch:
  - platform: gpio
    id: switch_1
    name: Dongle Power
    pin: P26
    icon: mdi:power-socket-uk
    on_turn_on:
      - light.turn_on: plug_led
    on_turn_off:
      - light.turn_off: plug_led
    restore_mode: ${relay_restore_mode}

status_led:
  pin:
    number: P6
    inverted: true

button:
  - platform: restart
    name: Restart

time:
  - platform: homeassistant
    id: homeassistant_time